packages: []
patchedDependencies:
  splitpanes@3.1.5: patches/splitpanes@3.1.5.patch
catalogs:
  dev:
    '@antfu/eslint-config': ^4.15.0
    '@intlify/eslint-plugin-vue-i18n': ^4.0.1
    '@unocss/eslint-plugin': ^66.2.3
    eslint: ^9.29.0
    eslint-plugin-format: ^1.0.1
    execa: ^9.6.0
    fast-glob: ^3.3.3
    rehype-external-links: ^3.0.0
    typescript: ^5.8.3
    vue-tsc: ^2.2.10
  frontend:
    '@shikijs/core': ^3.6.0
    '@shikijs/monaco': ^3.6.0
    '@volar/monaco': ~2.4.14
    '@vue/language-service': ^2.2.10
    '@webcontainer/api': ^1.6.1
    '@xterm/addon-fit': ^0.10.0
    '@xterm/xterm': ^5.5.0
    birpc: ^2.4.0
    floating-vue: ^5.2.2
    fuse.js: ^7.1.0
    jszip: ^3.10.1
    monaco-editor: ^0.50.0
    monaco-editor-core: ^0.50.0
    pathe: ^2.0.3
    shiki: ^3.6.0
    splitpanes: 3.1.5
    strip-json-comments: ^5.0.2
    theme-vitesse: ^0.8.3
    vscode-uri: ^3.1.0
    vue: ^3.5.17
    vue-router: ^4.5.1
  icons:
    '@iconify-json/carbon': ^1.2.9
    '@iconify-json/catppuccin': ^1.2.11
    '@iconify-json/logos': ^1.2.4
    '@iconify-json/ph': ^1.2.2
    '@iconify-json/svg-spinners': ^1.2.2
  nuxt:
    '@nuxt/content': ^3.6.0
    '@nuxt/devtools': ^2.5.0
    '@nuxt/eslint': ^1.4.1
    '@nuxt/icon': ^1.14.0
    '@nuxt/image': ^1.10.0
    '@nuxt/kit': ^3.17.5
    '@nuxtjs/color-mode': ^3.5.2
    '@nuxtjs/i18n': ^9.5.5
    '@nuxtjs/seo': ^3.1.0
    '@pinia/nuxt': ^0.11.1
    '@unocss/extractor-mdc': ^66.2.3
    '@unocss/nuxt': ^66.2.3
    '@vueuse/nuxt': ^13.3.0
    nuxi: ^3.25.1
    nuxt: ^3.17.5
onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
