name: autofix.ci

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  autofix:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Use Node.js lts/*
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install
        run: pnpm install

      - name: Lint
        run: pnpm run lint --fix

      - uses: autofix-ci/action@v1
